### ISSUE TITLE
Elaborar documento de qualidade para documentação

### ISSUE THREAD

**Issue by mansogf** [fga-eps-mds/2020.1-Grupo6#101]
**Descrição**

Elaborar documento de qualidade para documentação para não haver discrepâncias significativas de qualidade entre os documentos do time.

**Tarefas**
- [ ] Elaborar documento de qualidade para documentação

**Critérios de Aceitação**
- [ ] Validar com o time de gerência

**Comment by Mateusas3s** [comment]
Não vendo muita viabilidade nessa documentação decidimos por fechá-la até segunda ordem.
