### ISSUE TITLE
US 36 - Receber dados relevantes do VCU [INTEGRAÇÃO]

### ISSUE THREAD

**Issue by Guilherme-Aguiar** [fga-eps-mds/2020.1-Grupo6#155]
**Tipo de _issue_**

US 36 - Receber dados relevantes do VCU [INTEGRAÇÃO]  [User Story]  

**Descrição**

Integrar a api e banco de dados do time VCU da turma da Carla com a nossa seção de postagens. A integração da seção de dashboard fica para a próxima sprint.

**Tarefas**
- [x] Colocar o repositório VCU para rodar;
- [x] Conhecer sua api e o banco de dados;
- [x] Estabelecer uma estratégia para utilizar o endpoints deles nosso front-end;

**Critérios de Aceitação**
- [x] Integrar endpoints com impacto mínimo sob a estrutura atual do nosso front-end;

**Comment by Guilherme-Aguiar** [comment]
Se os endpoints deles não tiverem nada a ver com os nossos, e não der pra aproveitar, temos que saber logo @ismaelg456g @Vitorsulzbach

**Comment by Bruno-Felix** [comment]
Estamos abertos para conversa e possíveis ajustes no projeto.

Podem usar essa issue para listar tudo aquilo que o seu projeto precisa do nosso e ainda não foi atendido. Ficaremos atentos aqui.

Na medida do possível dentro dos 10 dias restantes faremos o que for necessário...

Obrigado.

**Comment by Bruno-Felix** [comment]
Também temos uma issue especializada para isso que resolvemos MUITAS coisas.

[#197](https://github.com/fga-eps-mds/2020.1-VC_Usuario/issues/197)

Podemos tentar dá um PR na devel com as mudanças já feitas para possivelmente ajudar o senhores.

**Comment by Bruno-Felix** [comment]
Opa. 

Percebemos que o senhores criaram uma branch para essa issue.

Podem nos explicar do que ela se trata?

https://github.com/fga-eps-mds/2020.1-VC_Usuario/commit/34e919b01e709d570d0b98f2427e95f5e04275e9

Esse commit insere coisas que não são do escopo do VCU.

Além de estar fora dos nossos padrões de contribuição.

**Comment by ismaelg456g** [comment]
@Bruno-Felix , Eu e o Vitor estamos trabalhando na integração dos posts do Back de vocês com o nosso Front. O que aconteceu é que precisávamos de algumas funcionalidades do seu Back que não estavam disponíveis, então criamos algumas funções para nos entregar alguns dados formatados para geração de gráficos.
Sobre a formatação, não tínhamos nos atentado a isso realmente. Vou dar uma olhada nas políticas de commits e branches, e iremos consertar a formatação.
Fora isso, nós encontramos alguns pequenos bugs no projeto de vocês. Mais tarde a gente vai relatar, mas no caso a gente relata nessa issue #197, ou criamos uma nova?

**Comment by Bruno-Felix** [comment]
> @Bruno-Felix , Eu e o Vitor estamos trabalhando na integração dos posts do Back de vocês com o nosso Front. O que aconteceu é que precisávamos de algumas funcionalidades do seu Back que não estavam disponíveis, então criamos algumas funções para nos entregar alguns dados formatados para geração de gráficos.
> Sobre a formatação, não tínhamos nos atentado a isso realmente. Vou dar uma olhada nas políticas de commits e branches, e iremos consertar a formatação.
> Fora isso, nós encontramos alguns pequenos bugs no projeto de vocês. Mais tarde a gente vai relatar, mas no caso a gente relata nessa issue #197, ou criamos uma nova?

Opa @ismaelg456g. Espero que tenha ficado claro que aquelas funções feitas na branch de auxilio de geração de gráficos não entrarão no projeto por não fazer parte do nosso escopo e não ter tido nenhuma conversa sobre durante as 14 semanas. Sugiro que reavaliem como será todo esse processo do lado de vocês.

Seria melhor criar outra issue para esses bugs e funcionalidades. Mas caso tenha algo novo que exige um certo trabalho, acredito que não será feito. Essa semana já foi de correção e trabalho em diversos pontos do projeto e semana que vem acredito que não terá muito trabalho no quesito código.

**Comment by Bruno-Felix** [comment]
Conversei com o @Vitorsulzbach para criar e entregar essa listar de tudo.
 
Mas precisamos disso com urgência para avaliar e planejar o que pode ou não pode ser feito.

**Comment by Bruno-Felix** [comment]
Aplicação: https://vc-usuario-frontend.herokuapp.com/
API: https://vc-usuario-backend.herokuapp.com/

**Comment by Bruno-Felix** [comment]
> Aplicação: https://vc-usuario-frontend.herokuapp.com/
> API: https://vc-usuario-backend.herokuapp.com/

Usem com moderação.
O banco de dados não é tão gordo assim. kkkk

**Comment by Guilherme-Aguiar** [comment]
Muito obrigado @Bruno-Felix !
