### ISSUE TITLE
Definição de Tema

### ISSUE THREAD

**Issue by Mateusas3s** [fga-eps-mds/2020.1-Grupo6#2]
Selecionar tema do projeto visando atender alguma necessidade pública real

**Comment by mansogf** [comment]
Atualizar essa issue após reunião de quinta com o @Mateusas3s e @Guilherme-Aguiar .

**Comment by Mateusas3s** [comment]
Tema do Projeto: 
- [TP1] Auxiliar os gestores da UnB na captura de feedback da comunidade acadêmica sobre suas necessidades;
- [TP2] Auxiliá os gestores da UnB na comunicação das tomadas de decisão relacionadas à resolução dos problemas expostos pela comunidade acadêmica.

O tema foi dividido entre dois grupos de desenvolvimento:
- Grupo responsável pelo TP01 [Vamos Cuidar App](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar)
- Grupo responsável pelo TP02 [Vamos Cuidar Gestor](https://github.com/fga-eps-mds/2020.1-Grupo6)
