### ISSUE TITLE
Definição de Escopo do Projeto

### ISSUE THREAD

**Issue by Mateusas3s** [fga-eps-mds/2020.1-Grupo6#3]
- [x] Reunião com o cliente(issue #55 )

**Comment by mansogf** [comment]
@Guilherme-Aguiar , pode atualizar o status dessa issue aqui no comentário ?

**Comment by mansogf** [comment]
Será importante criar uma pasta chamada "interviews" na pasta "docs"para subir as atas de entrevistas.

## Importante: Fazer isso depois que o PR #27 for "merjado" na master.

**Comment by Mateusas3s** [comment]
Tema do Projeto: 
- [TP1] Auxiliar os gestores da UnB na captura de feedback da comunidade acadêmica sobre suas necessidades;
- [TP2] Auxiliá os gestores da UnB na comunicação das tomadas de decisão relacionadas à resolução dos problemas expostos pela comunidade acadêmica.

O tema foi dividido entre dois grupos de desenvolvimento:
- Grupo responsável pelo TP01 [Vamos Cuidar App](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar)
- Grupo responsável pelo TP02 [Vamos Cuidar Gestor](https://github.com/fga-eps-mds/2020.1-Grupo6)
