### ISSUE TITLE
Visão Geral do Produto - DocVisão

### ISSUE THREAD

**Issue by brunocmo** [fga-eps-mds/2020.1-Grupo6#33]
**Tipo de _issue_**

Elaborar Documento de Visão [TS- #23 ]
Tarefa: Visão Geral do Produto  

**Descrição**

Inclusão das informações sobre a visão geral do produto.

**Tarefas**
- [x] Perspectivas do produto
- [x] Resumo das Capacidades
- [x] Suposições de dependências
- [x] Custo e precificação
- [x] Licenciamento e Instalação

**Comment by Guilherme-Aguiar** [comment]
Boa @brunocmo ! dei uma atualizada nessa issue para condizer com a história de usuário correspondente. Vc pode ver as histórias de usuário [nesse link](https://fga-eps-mds.github.io/2020.1-Grupo6/org_artifacts/requirements_engineering/#3_2). No caso o tópico que você escolheu seria uma tarefa dentro da história de usuário US001.

**Comment by brunocmo** [comment]
> Boa @brunocmo ! dei uma atualizada nessa issue para condizer com a história de usuário correspondente. Vc pode ver as histórias de usuário [nesse link](https://fga-eps-mds.github.io/2020.1-Grupo6/org_artifacts/requirements_engineering/#3_2). No caso o tópico que você escolheu seria uma tarefa dentro da história de usuário US001.

Valeu cara, isso é bom. Eu ainda tava com dúvida sobre os templates das issues.
