### ISSUE TITLE
Elaborar o Documento de Arquitetura do Projeto

### ISSUE THREAD

**Issue by Guilherme-Aguiar** [fga-eps-mds/2020.1-Grupo6#52]
**Tipo de _issue_**

US003 - Elaborar o Documento de Arquitetura do Projeto

**Descrição**

Nessa user storie, os alunos de MDS devem elaborar o documento de arquitetura com o objetivo de fornecer uma visão arquitetural abrangente do sistema Vamos Cuidar Gestão, por meio de diversas visões arquiteturais para representar diferentes aspectos da aplicação.

**Tarefas**
- [x] Introdução
- [x] Representação Arquitetural 
- [x] Restrições e Metas Arquiteturais 
- [x] Visão de Casos de Uso
- [x] Visão Lógica

**Critérios de Aceitação**
- [x] Todas tarefas concluídas.

**Comment by brunocmo** [comment]
Realizando a parte Visão de Casos de Uso.

**Comment by brunocmo** [comment]
Esperando a revisão sobre Visão de Casos de Uso (#63)

**Comment by ismaelg456g** [comment]
Realizando o tópico de visão lógica.

**Comment by tomasvelos0** [comment]
Realizando o tópico 3 sobre Restrições e Metas Arquiteturais.

**Comment by julianavalle** [comment]
Realizando o tópico 2 - Representação Arquitetural

**Comment by mansogf** [comment]
@Mateusas3s , como tá o andamento dessa issue?
