### ISSUE TITLE
Criar artefatos orgnizacionais do repositório

### ISSUE THREAD

**Issue by Mateusas3s** [fga-eps-mds/2020.1-Grupo6#6]
- [x] Issue Template
- [x] Pull Request Template
- [x] Code of Conduct
- [x] License
- [x] Contributing
- [x] Description

**Comment by mansogf** [comment]
Além dos artefatos acima listados, foram criados os templates de commit, branch e files & folders.

**Comment by mansogf** [comment]
Falta agora o código de conduta, de contribuição.

**Comment by mansogf** [comment]
Estou um pouco confuso com o que seria "Description". Seria isso o software_configuration_management?

**Comment by mansogf** [comment]
> Falta agora o código de conduta, de contribuição.

Feito.

**Comment by Mateusas3s** [comment]
Artefatos já no git pages do repositório: [Git Pages](https://fga-eps-mds.github.io/2020.1-Grupo6/)
